main_app/urls.py
from django.urls import include, path
from . import views


app_name = "main_app"

urlpatterns = [
    path("", views.home, name="home"),
    # path("login_user", views.login_user, name="login_user"),
    path("logout", views.logout_user, name="logout_user"),
    path("register", views.register_user, name="register_user"),
    path("record/<int:pk>", views.customer_record, name="record"),
    path("delete_record/<int:pk>", views.delete_record, name="delete_record"),
    path("add_record/", views.add_record, name="add_record"),
    path("update_record/<int:pk>", views.update_record, name="update_record"),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls", namespace="main_app")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models

# Create your models here.


class Record(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Record


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        label="",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Email Address"}
        ),
    )
    first_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "First Name"}
        ),
    )
    last_name = forms.CharField(
        label="",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Last Name"}
        ),
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields["username"].widget.attrs["class"] = "form-control"
        self.fields["username"].widget.attrs["placeholder"] = "User Name"
        self.fields["username"].label = ""
        self.fields[
            "username"
        ].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields["password1"].widget.attrs["class"] = "form-control"
        self.fields["password1"].widget.attrs["placeholder"] = "Password"
        self.fields["password1"].label = ""
        self.fields[
            "password1"
        ].help_text = "<ul class=\"form-text text-muted small\"><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul>"

        self.fields["password2"].widget.attrs["class"] = "form-control"
        self.fields["password2"].widget.attrs["placeholder"] = "Confirm Password"
        self.fields["password2"].label = ""
        self.fields[
            "password2"
        ].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'


# Create Add Record Form
class AddRecordForm(forms.ModelForm):
    first_name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "First Name", "class": "form-control"}
        ),
        label="",
    )
    last_name = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "Last Name", "class": "form-control"}
        ),
        label="",
    )
    email = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "Email", "class": "form-control"}
        ),
        label="",
    )
    phone = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "Phone", "class": "form-control"}
        ),
        label="",
    )
    address = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "Address", "class": "form-control"}
        ),
        label="",
    )
    city = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "City", "class": "form-control"}
        ),
        label="",
    )
    state = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "State", "class": "form-control"}
        ),
        label="",
    )
    zipcode = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={"placeholder": "Zipcode", "class": "form-control"}
        ),
        label="",
    )

    class Meta:
        model = Record
        exclude = ("user",)

main_app/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import *

# Create your views here.


def home(request):
    records = Record.objects.all()
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "You have successfully logged in")
            return redirect("/")
        else:
            messages.info(request, "Username or Password is incorrect")
            return render(request, "main_app/home.html")
    return render(request, "main_app/home.html", {"records": records})


def logout_user(request):
    logout(request)
    messages.success(request, "You have successfully logged out")
    return redirect("/")


def register_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, "You Have Successfully Registered! Welcome!")
            return redirect("/")
    else:
        form = SignUpForm()
        return render(request, "home/register.html", {"form": form})

    return render(request, "home/register.html", {"form": form})


def add_record(request):
    form = AddRecordForm(request.POST or None)
    if request.method == "POST":
        if request.user.is_authenticated:
            if form.is_valid():
                form.save()
                messages.success(request, "Record Added...")
                return redirect("/")
        else:
            messages.success(request, "You Must Be Logged In...")
            return redirect("/")
    return render(request, "main_app/add_record.html", {"form": form})


def customer_record(request, pk):
    if request.user.is_authenticated:
        customer_record = Record.objects.get(id=pk)
        return render(
            request, "main_app/record.html", {"customer_record": customer_record}
        )
    else:
        messages.success(request, "You Must Be Logged In To View That Page...")
        return redirect("/")


def update_record(request, pk):
    current_record = Record.objects.get(id=pk)
    form = AddRecordForm(request.POST or None, instance=current_record)
    if request.user.is_authenticated:
        if form.is_valid():
            form.save()
            messages.success(request, "Record Has Been Updated!")
            return redirect("/")
    else:
        messages.success(request, "You Must Be Logged In To Do That ")
        return redirect("/")
    return render(request, "main_app/update_record.html", {"form": form})


def delete_record(request, pk):
    if request.user.is_authenticated:
        delete_it = Record.objects.get(id=pk)
        delete_it.delete()
        messages.success(request, "Record Deleted Successfully ")
        return redirect("/")
    else:
        messages.success(request, "You Must Be Logged In To Do That ")
        return redirect("/")

main_app/templates/main_app/add_record.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
<h1>Add Record</h1>
<br/>

<form method="POST" action="{% url 'main_app:add_record' %}">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Add Record</button>
   <a href="{% url 'main_app:home' %}" class="btn btn-secondary">Back</a>

</form>

</div>

{% endblock %}

main_app/templates/main_app/home.html
{% extends 'base.html' %}

{% block content %}



{% if user.is_authenticated %}


<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">City</th>
      <th scope="col">State</th>
      <th scope="col">Zipcode</th>
      <th scope="col">Created At</th>
      <th scope="col">ID</th>
    </tr>
  </thead>
  <tbody>
    
{% if records %}
	{% for record in records %}
		<tr>
			<td>{{ record.first_name }} {{ record.last_name }}</td>
			<td>{{ record.email }}</td>
			<td>{{ record.phone }}</td>
			<td>{{ record.address }}</td>
			<td>{{ record.city }}</td>
			<td>{{ record.state }}</td>
			<td>{{ record.zipcode }}</td>
			<td>{{ record.created_at }}</td>
			<td><a href="{% url 'main_app:record' record.id %}">{{ record.id }}</a></td>
		</tr>
	{% endfor %}

{% endif %}

	
	  </tbody>
	</table>





{% else %}

<div class="col-md-6 offset-md-3">
<h1>Login</h1>
<br/>

<form method="POST" action="{% url 'main_app:home' %}">
	{% csrf_token %}

  <div class="mb-3">
    <input type="text" class="form-control" name="username", placeholder="Username" required>
    
  </div><br/>
  <div class="mb-3">
    <input type="password" class="form-control" name="password", placeholder="Password" required>
  </div>
  <br/>
  <button type="submit" class="btn btn-secondary">Login</button>

</form>



{% endif %}

{% endblock %}

main_app/templates/main_app/record.html
{% extends 'base.html' %}
{% block content %}



<div class="card">
  <div class="card-header"><strong>
    	{{ customer_record.first_name }} 
		{{ customer_record.last_name }}</strong>
  </div>
  <div class="card-body">



<p class="card-text">
<strong>Email: </strong>{{ customer_record.email }}</p>

<p class="card-text">
<strong>Phone: </strong>{{ customer_record.phone }}
</p>

<p class="card-text">
<strong>Address: </strong>{{ customer_record.address }}</p>

<p class="card-text">
<strong>City: </strong>{{ customer_record.city }}</p>

<p class="card-text">
<strong>State: </strong>{{ customer_record.state }}</p>

<p class="card-text">
<strong>Zipcode: </strong>{{ customer_record.zipcode }}</p>

<p class="card-text">
<strong>Create At: </strong>{{ customer_record.created_at }}</p>

<p class="card-text">
<strong>ID: </strong>{{ customer_record.id }}</p>
    
    
  </div>
</div>

<br/><br/>
<a href="{% url 'main_app:home' %}" class="btn btn-secondary">Back</a>

<a href="{% url 'main_app:delete_record' customer_record.id %}" class="btn btn-danger">Delete</a>

<a href="{% url 'main_app:update_record' customer_record.id %}" class="btn btn-secondary">Update Record</a>
		

{% endblock %}

main_app/templates/main_app/register.html
{% extends 'base.html' %}
{% block content %}


<div class="col-md-6 offset-md-3">
<h1>Register</h1>
<br/>

<form method="POST" action="">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Your Form Has Errors
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-secondary">Register</button>
	</form>



</div>

{% endblock %}

main_app/templates/main_app/update_record.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 offset-md-3">
<h1>Add Record</h1>
<br/>

<form method="POST">
	{% csrf_token %}

	{{ form.as_p }}

<br/>
  <button type="submit" class="btn btn-secondary">Update Record</button>

</form>


</div>

{% endblock %}